enyo.depends(
    "helper.js",
    "shared/array.js",
    "shared/comment.js",
    "shared/expression.js",
    "shared/property.js",
    "shared/properties.js",
    "kind",
    "object",
    "property"
    );